apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: iamroles.operator.aws.amazon.com
spec:
  group: operator.aws.amazon.com
  names:
    kind: IamRole
    listKind: IamRoleList
    plural: iamroles
    singular: iamrole
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
